# Generated by Django 5.0.3 on 2024-04-14 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='user_id',
            new_name='user',
        ),
    ]
