# Generated by Django 5.0.3 on 2024-04-14 13:11

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_user_id_postmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dislikemodel',
            name='dtime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='likemodel',
            name='dtime',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 14, 13, 11, 50, 826197, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
