# Generated by Django 5.0.3 on 2024-04-14 14:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_dislikemodel_dtime_likemodel_dtime'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likemodel',
            unique_together={('post_id', 'liked_by')},
        ),
    ]
