# Generated by Django 5.0.3 on 2024-04-15 00:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_likemodel_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='dislike_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='dislikemodel',
            unique_together={('post_id', 'disliked_by')},
        ),
    ]
